// Generated by Tezz (तेज़) Compiler v0.2.0
// Target: worker
// Generated at: 2026-08-30T13:00:30.359Z

import createClient from 'tezz-database';

// ─────────────────────────────────────────
// Tezz Service: AnonymousService_5b502t
// ─────────────────────────────────────────

const __tezz_routes_AnonymousService_5b502t = [];

__tezz_routes_AnonymousService_5b502t.push({
  method: 'GET',
  pattern: new RegExp('^\/$'),
  paramNames: [],
  handler: async function(__tezz_request, __tezz_params) {
    const request = __tezz_request;
    const params = __tezz_params;
    return { __tezz_status: 200, __tezz_body: { status: 'healthy', service: 'Contact API' } };
  }
});

__tezz_routes_AnonymousService_5b502t.push({
  method: 'GET',
  pattern: new RegExp('^\/api\/contacts$'),
  paramNames: [],
  handler: async function(__tezz_request, __tezz_params) {
    const request = __tezz_request;
    const params = __tezz_params;
    return { __tezz_status: 200, __tezz_body: { success: true, contacts: [{ name: 'Abhinav', email: 'abhinav@example.com', message: 'Tezz is blazing fast!' }, { name: 'Batman', email: 'batman@wayne.com', message: 'We should use Tezz!' }, { name: 'Pikachu', email: 'pika@chu.com', message: 'Zero-overhead JS without node_modules' }] } };
  }
});

__tezz_routes_AnonymousService_5b502t.push({
  method: 'POST',
  pattern: new RegExp('^\/api\/contact$'),
  paramNames: [],
  handler: async function(__tezz_request, __tezz_params) {
    const request = __tezz_request;
    const params = __tezz_params;
    let body = (await request.json());
    let name = body.name;
    let email = body.email;
    let message = body.message;
    if ((((!name) || (!email)) || (!message))) {
      return { __tezz_status: 200, __tezz_body: { success: false, error: 'Missing required fields' } };
      return;
    }
    let db = createClient({ url: env.TURSO_URL, token: env.TURSO_TOKEN });
    try {
      let result = (await db.execute('INSERT INTO contacts (name, email, message) VALUES (?, ?, ?)', [name, email, message]));
      if (result.ok) {
        return { __tezz_status: 200, __tezz_body: { success: true } };
      }
    } catch (err) {
      return { __tezz_status: 200, __tezz_body: { success: false, error: 'Database error' } };
    }
  }
});


export default {
  async fetch(req, env, ctx) {
    if (req.method === 'OPTIONS') {
      return new Response(null, {
        status: 204,
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
          'Access-Control-Allow-Headers': 'Content-Type, Authorization',
        },
      });
    }

    const __url = new URL(req.url);
    const __method = req.method;
    const __path = __url.pathname;

    for (const __route of __tezz_routes_AnonymousService_5b502t) {
      const __match = __route.pattern.exec(__path);
      if (__match && __route.method === __method) {
        const __params = {};
        __route.paramNames.forEach((n, i) => { __params[n] = __match[i + 1]; });

        let __bodyData = {};
        try { __bodyData = await req.json(); } catch {}

        const __request = {
          method: __method,
          url: __path,
          headers: Object.fromEntries(req.headers),
          json() { return __bodyData; },
          text() { return JSON.stringify(__bodyData); },
          query: Object.fromEntries(__url.searchParams),
        };

        try {
          const __result = await __route.handler(__request, __params);
          const __status = __result && __result.__tezz_status ? __result.__tezz_status : 200;
          const __respBody = __result && __result.__tezz_body ? __result.__tezz_body : (__result || {});
          return new Response(JSON.stringify(__respBody), {
            status: __status,
            headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
          });
        } catch (__err) {
          return new Response(JSON.stringify({ error: __err.message }), {
            status: 500,
            headers: { 'Content-Type': 'application/json' },
          });
        }
      }
    }

    return new Response(JSON.stringify({ error: 'Not Found', path: __path }), {
      status: 404,
      headers: { 'Content-Type': 'application/json' },
    });
  },
};
