// Generated by Tezz (तेज़) Compiler v0.2.0
// Target: worker
// Generated at: 2026-09-14T00:46:03.319Z

import libsql from './libsql-wrapper.js';

// ─────────────────────────────────────────
// Tezz Service: UniCoreAPI
// ─────────────────────────────────────────

const __tezz_routes_UniCoreAPI = [];

__tezz_routes_UniCoreAPI.push({
  method: 'GET',
  pattern: new RegExp('^\/health$'),
  paramNames: [],
  handler: async function(__tezz_request, __tezz_params, env) {
    const request = __tezz_request;
    const params = __tezz_params;
    return { __tezz_status: 200, __tezz_body: { status: 'healthy', service: 'UniCoreAPI' } };
  }
});

__tezz_routes_UniCoreAPI.push({
  method: 'GET',
  pattern: new RegExp('^\/init$'),
  paramNames: [],
  handler: async function(__tezz_request, __tezz_params, env) {
    const request = __tezz_request;
    const params = __tezz_params;
    let db = libsql.createClient({ url: env.TURSO_URL, authToken: env.TURSO_TOKEN });
    (await db.execute('DROP TABLE IF EXISTS students'));
    (await db.execute('DROP TABLE IF EXISTS hostels'));
    (await db.execute('DROP TABLE IF EXISTS enrollments'));
    (await db.execute('DROP TABLE IF EXISTS library'));
    (await db.execute('CREATE TABLE students (id INTEGER PRIMARY KEY, roll TEXT UNIQUE, name TEXT, department TEXT, year INTEGER, gpa REAL)'));
    (await db.execute('CREATE TABLE hostels (id INTEGER PRIMARY KEY, student_roll TEXT, block TEXT, room TEXT, status TEXT)'));
    (await db.execute('CREATE TABLE enrollments (id INTEGER PRIMARY KEY, student_roll TEXT, course_name TEXT, grade TEXT)'));
    (await db.execute('CREATE TABLE library (id INTEGER PRIMARY KEY, student_roll TEXT, book_title TEXT, due_date TEXT)'));
    (await db.execute({ sql: 'INSERT INTO students (roll, name, department, year, gpa) VALUES (?, ?, ?, ?, ?)', args: ['1024030440', 'Abhinav Kumar Singh', 'Computer Science', 3, 9.8] }));
    (await db.execute({ sql: 'INSERT INTO hostels (student_roll, block, room, status) VALUES (?, ?, ?, ?)', args: ['1024030440', 'Block M', 'Room 405', 'Allotted'] }));
    (await db.execute({ sql: 'INSERT INTO enrollments (student_roll, course_name, grade) VALUES (?, ?, ?)', args: ['1024030440', 'Distributed Systems', 'A+'] }));
    (await db.execute({ sql: 'INSERT INTO enrollments (student_roll, course_name, grade) VALUES (?, ?, ?)', args: ['1024030440', 'Cloud Computing', 'A'] }));
    (await db.execute({ sql: 'INSERT INTO library (student_roll, book_title, due_date) VALUES (?, ?, ?)', args: ['1024030440', 'Designing Data-Intensive Applications', '2026-09-30'] }));
    return { __tezz_status: 200, __tezz_body: { success: true, message: 'Database initialized with full seed data!' } };
  }
});

__tezz_routes_UniCoreAPI.push({
  method: 'GET',
  pattern: new RegExp('^\/api\/student\/([^\\/]+)\/dashboard$'),
  paramNames: ["roll"],
  handler: async function(__tezz_request, __tezz_params, env) {
    const request = __tezz_request;
    const params = __tezz_params;
    let db = libsql.createClient({ url: env.TURSO_URL, authToken: env.TURSO_TOKEN });
    let roll = params.roll;
    let studentRes = (await db.execute({ sql: 'SELECT * FROM students WHERE roll = ?', args: [roll] }));
    if ((studentRes.rows.length == 0)) {
      return { __tezz_status: 404, __tezz_body: { error: 'Student not found' } };
    } else {
      let hostelRes = (await db.execute({ sql: 'SELECT * FROM hostels WHERE student_roll = ?', args: [roll] }));
      let enrollRes = (await db.execute({ sql: 'SELECT * FROM enrollments WHERE student_roll = ?', args: [roll] }));
      let libraryRes = (await db.execute({ sql: 'SELECT * FROM library WHERE student_roll = ?', args: [roll] }));
      let hostelData = null;
      if ((hostelRes.rows.length > 0)) {
        hostelData = hostelRes.rows[0];
      }
      return { __tezz_status: 200, __tezz_body: {
        student: studentRes.rows[0],
        hostel: hostelData,
        enrollments: enrollRes.rows,
        library: libraryRes.rows
      } };
    }
  }
});


export default {
  async fetch(req, env, ctx) {
    if (req.method === 'OPTIONS') {
      return new Response(null, {
        status: 204,
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
          'Access-Control-Allow-Headers': 'Content-Type, Authorization',
        },
      });
    }

    const __url = new URL(req.url);
    const __method = req.method;
    const __path = __url.pathname;

    for (const __route of __tezz_routes_UniCoreAPI) {
      const __match = __route.pattern.exec(__path);
      if (__match && __route.method === __method) {
        const __params = {};
        __route.paramNames.forEach((n, i) => { __params[n] = __match[i + 1]; });

        let __bodyData = {};
        try { __bodyData = await req.json(); } catch {}

        const __request = {
          method: __method,
          url: __path,
          headers: Object.fromEntries(req.headers),
          json() { return __bodyData; },
          text() { return JSON.stringify(__bodyData); },
          query: Object.fromEntries(__url.searchParams),
        };

        try {
          const __result = await __route.handler(__request, __params, env);
          const __status = __result && __result.__tezz_status ? __result.__tezz_status : 200;
          const __respBody = __result && __result.__tezz_body ? __result.__tezz_body : (__result || {});
          return new Response(JSON.stringify(__respBody), {
            status: __status,
            headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
          });
        } catch (__err) {
          return new Response(JSON.stringify({ error: __err.message }), {
            status: 500,
            headers: { 'Content-Type': 'application/json' },
          });
        }
      }
    }

    return new Response(JSON.stringify({ error: 'Not Found', path: __path }), {
      status: 404,
      headers: { 'Content-Type': 'application/json' },
    });
  },
};
