// Tezz Language — Code Generator
const stdlib = require('./stdlib.js');

// Walks the AST and emits JavaScript code
// Supports two targets: 'node' (Node.js) and 'worker' (Cloudflare Workers)

class CodeGenerator {
  constructor(ast, options = {}) {
    this.ast = ast;
    this.target = options.target || 'node';
    this.indent = 0;
    this.output = '';
    this.services = [];
    this.macros = {};
    this.usedStdLibs = new Set();
  }

  // --- Output helpers ---

  emit(code) { this.output += code; }
  pad() { return '  '.repeat(this.indent); }
  line(code) { this.output += this.pad() + code + '\n'; }

  // === ENTRY POINT ===

  generate() {
    this.emit('// Generated by Tezz (तेज़) Compiler v0.2.0\n');
    this.emit(`// Target: ${this.target}\n`);
    this.emit(`// Generated at: ${new Date().toISOString()}\n\n`);

    // Collect services for later
    for (const node of this.ast.body) {
      if (node.type === 'ServiceDeclaration') this.services.push(node);
    }

    // Emit non-service top-level code first
    for (const node of this.ast.body) {
      if (node.type !== 'ServiceDeclaration') this.genStmt(node);
    }

    // Emit services
    for (const svc of this.services) {
      this.genService(svc);
    }

    return { code: this.output, stdLibs: Array.from(this.usedStdLibs) };
  }

  // === STATEMENTS ===

  genStmt(node) {
    switch (node.type) {
      case 'VariableDeclaration':  return this.genVarDecl(node);
      case 'FunctionDeclaration':  return this.genFnDecl(node);
      case 'ServiceDeclaration':   return this.genService(node);
      case 'ReturnStatement':      return this.genReturn(node);
      case 'RespondStatement':     return this.genRespond(node);
      case 'IfStatement':          return this.genIf(node);
      case 'ForStatement':         return this.genFor(node);
      case 'WhileStatement':       return this.genWhile(node);
      case 'TryCatchStatement':    return this.genTryCatch(node);
      case 'PrintStatement':       return this.genPrint(node);
      case 'ExpressionStatement':  return this.line(this.genExpr(node.expression) + ';');
      case 'ImportStatement':      return this.genImport(node);
      case 'ExportStatement':      return this.genExport(node);
      case 'BackgroundStatement':  return this.genBackground(node);
      case 'SpawnStatement':       return this.genSpawn(node);
      case 'EnumDeclaration':      return this.genEnum(node);
      case 'TraitDeclaration':     return this.genTrait(node);
      case 'MacroDeclaration':     return this.genMacro(node);

      default: throw new Error(`[Tezz Codegen] Unknown statement: ${node.type}`);
    }
  }

  genVarDecl(node) {
    const kind = node.kind || 'let';
    this.line(`${kind} ${node.name} = ${this.genExpr(node.value)};`);
  }

  genFnDecl(node) {
    const params = node.params.map(p => p.name).join(', ');
    const asyncPrefix = node.isAsync ? 'async ' : '';
    this.line(`${asyncPrefix}function ${node.name}(${params}) {`);
    this.indent++;
    for (const s of node.body) this.genStmt(s);
    this.indent--;
    this.line('}');
    this.emit('\n');
  }

  genReturn(node) {
    if (node.value) {
      this.line(`return ${this.genExpr(node.value)};`);
    } else {
      this.line('return;');
    }
  }

  genRespond(node) {
    const status = node.status || 200;
    const body = this.genExpr(node.body);
    this.line(`return { __tezz_status: ${status}, __tezz_body: ${body} };`);
  }

  genIf(node) {
    this.line(`if (${this.genExpr(node.condition)}) {`);
    this.indent++;
    for (const s of node.consequent) this.genStmt(s);
    this.indent--;
    if (node.alternate) {
      if (node.alternate.type === 'IfStatement') {
        this.emit(this.pad() + '} else ');
        // Inline the if (no extra line break)
        this.genIf(node.alternate);
        return;
      } else {
        this.line('} else {');
        this.indent++;
        for (const s of node.alternate) this.genStmt(s);
        this.indent--;
      }
    }
    this.line('}');
  }

  genFor(node) {
    this.line(`for (const ${node.variable} of ${this.genExpr(node.iterable)}) {`);
    this.indent++;
    for (const s of node.body) this.genStmt(s);
    this.indent--;
    this.line('}');
  }

  genWhile(node) {
    this.line(`while (${this.genExpr(node.condition)}) {`);
    this.indent++;
    for (const s of node.body) this.genStmt(s);
    this.indent--;
    this.line('}');
  }

  genTryCatch(node) {
    this.line(`try {`);
    this.indent++;
    for (const s of node.tryBody) this.genStmt(s);
    this.indent--;
    this.line(`} catch (${node.errorVar}) {`);
    this.indent++;
    for (const s of node.catchBody) this.genStmt(s);
    this.indent--;
    this.line(`}`);
  }

  genPrint(node) {
    const args = node.args.map(a => this.genExpr(a)).join(', ');
    this.line(`console.log(${args});`);
  }

genImport(node) {
    if (node.source.startsWith('tezz:')) {
      const lib = node.source.substring(5);
      if (['auth', 'validator', 'openapi', 'upload'].includes(lib)) {
        this.usedStdLibs.add(lib);
        const pkgName = 'tezz-' + lib;
        if (this.target === 'worker') {
          this.line(`import ${node.name} from '${pkgName}';`);
        } else {
          this.line(`const ${node.name} = require('${pkgName}');`);
        }
      } else {
        throw new Error(`[Tezz Codegen] Unknown standard library: ${node.source}`);
      }
      return;
    }

    if (this.target === 'worker') {
      this.line(`import ${node.name} from '${node.source}';`);
    } else {
      this.line(`const ${node.name} = require('${node.source}');`);
    }
  }




  genEnum(node) {
    const obj = node.variants.map(v => `${v}: "${v}"`).join(', ');
    this.line(`const ${node.name} = Object.freeze({ ${obj} });`);
  }

  genTrait(node) {
    this.line(`// Trait: ${node.name} (Compile-time only)`);
  }

  genMacro(node) {
    this.macros[node.name] = node;
    this.line(`// Macro: ${node.name} (Compile-time only)`);
  }

  expandMacro(macro, args) {
    const env = {};
    macro.params.forEach((p, i) => { env[p] = args[i]; });
    
    const walk = (n) => {
      if (!n) return n;
      if (Array.isArray(n)) return n.map(walk);
      if (typeof n !== 'object') return n;
      
      if (n.type === 'Identifier' && env[n.name]) {
        return env[n.name];
      }
      
      const copy = {};
      for (const key in n) copy[key] = walk(n[key]);
      return copy;
    };
    return walk(macro.body);
  }

  genSpawn(node) {
    if (this.target === 'worker') {
      this.line(`((async () => {`);
      this.indent++;
      for (const s of node.body) this.genStmt(s);
      this.indent--;
      this.line(`})());`);
    } else {
      this.line(`const { Worker } = require('worker_threads');`);
      this.line(`new Worker(\`const { parentPort } = require('worker_threads');`);
      this.line(`(async () => {`);
      this.indent++;
      for (const s of node.body) this.genStmt(s);
      this.indent--;
      this.line(`})();\`, { eval: true });`);
    }
  }

  genBackground(node) {
    if (this.target === 'worker') {
      this.line(`ctx.waitUntil((async () => {`);
      this.indent++;
      for (const s of node.body) this.genStmt(s);
      this.indent--;
      this.line(`})());`);
    } else {
      this.line(`Promise.resolve().then(async () => {`);
      this.indent++;
      for (const s of node.body) this.genStmt(s);
      this.indent--;
      this.line(`});`);
    }
  }

  genExport(node) {
    this.genStmt(node.declaration);
    const name = node.declaration.name;
    if (name) {
      if (this.target === 'worker') {
        this.line(`export { ${name} };`);
      } else {
        this.line(`module.exports.${name} = ${name};`);
      }
    }
  }

  // === SERVICE & ROUTES ===

  genService(node) {
    const name = node.name;
    const port = this.genExpr(node.port);

    this.emit('\n');
    this.line(`// ─────────────────────────────────────────`);
    this.line(`// Tezz Service: ${name}`);
    this.line(`// ─────────────────────────────────────────`);
    this.emit('\n');
    this.line(`const __tezz_routes_${name} = [];`);
    this.emit('\n');

    // Register each route
    for (const route of node.routes) {
      if (route.type === 'RouteDeclaration') {
        this.genRouteReg(route, name);
      } else {
        this.genStmt(route);
      }
    }

    this.emit('\n');

    // Emit the server
    if (this.target === 'worker') {
      this.genWorkerServer(name);
    } else {
      this.genNodeServer(name, port);
    }
  }

  genRouteReg(node, svcName) {
    // Convert /users/:id → regex with param extraction
    const paramNames = [];
    let pattern = node.path.replace(/:(\w+)/g, (_, p) => {
      paramNames.push(p);
      return '([^\\/]+)';
    });
    pattern = '^' + pattern.replace(/\//g, '\\/') + '$';

    this.line(`__tezz_routes_${svcName}.push({`);
    this.indent++;
    this.line(`method: '${node.method}',`);
    this.line(`pattern: new RegExp('${pattern}'),`);
    this.line(`paramNames: ${JSON.stringify(paramNames)},`);
    this.line(`handler: async function(__tezz_request, __tezz_params) {`);
    this.indent++;
    // Expose request and params as local variables
    this.line(`const request = __tezz_request;`);
    this.line(`const params = __tezz_params;`);
    for (const s of node.body) this.genStmt(s);
    this.indent--;
    this.line(`}`);
    this.indent--;
    this.line(`});`);
    this.emit('\n');
  }

  // --- Node.js Server ---
  genNodeServer(svcName, port) {
    this.line(`const http = require('http');`);
    this.emit('\n');

    this.line(`const __tezz_server_${svcName} = http.createServer(async (req, res) => {`);
    this.indent++;

    // CORS preflight
    this.line(`if (req.method === 'OPTIONS') {`);
    this.indent++;
    this.line(`res.writeHead(204, {`);
    this.indent++;
    this.line(`'Access-Control-Allow-Origin': '*',`);
    this.line(`'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',`);
    this.line(`'Access-Control-Allow-Headers': 'Content-Type, Authorization',`);
    this.indent--;
    this.line(`});`);
    this.line(`res.end();`);
    this.line(`return;`);
    this.indent--;
    this.line(`}`);
    this.emit('\n');

    this.line(`const __url = new URL(req.url, 'http://localhost');`);
    this.line(`const __method = req.method;`);
    this.line(`const __path = __url.pathname;`);
    this.emit('\n');

    // Body parsing
    this.line(`let __body = '';`);
    this.line(`await new Promise((resolve) => {`);
    this.indent++;
    this.line(`req.on('data', (chunk) => { __body += chunk; });`);
    this.line(`req.on('end', resolve);`);
    this.indent--;
    this.line(`});`);
    this.emit('\n');

    // Route matching
    this.line(`for (const __route of __tezz_routes_${svcName}) {`);
    this.indent++;
    this.line(`const __match = __route.pattern.exec(__path);`);
    this.line(`if (__match && __route.method === __method) {`);
    this.indent++;

    this.line(`const __params = {};`);
    this.line(`__route.paramNames.forEach((n, i) => { __params[n] = __match[i + 1]; });`);
    this.emit('\n');

    // Build request object
    this.line(`const __request = {`);
    this.indent++;
    this.line(`method: __method,`);
    this.line(`url: __path,`);
    this.line(`headers: req.headers,`);
    this.line(`json() { try { return JSON.parse(__body || '{}'); } catch { return {}; } },`);
    this.line(`text() { return __body; },`);
    this.line(`query: Object.fromEntries(__url.searchParams),`);
    this.indent--;
    this.line(`};`);
    this.emit('\n');

    // Call handler
    this.line(`try {`);
    this.indent++;
    this.line(`const __result = await __route.handler(__request, __params);`);
    this.line(`const __status = __result && __result.__tezz_status ? __result.__tezz_status : 200;`);
    this.line(`const __respBody = __result && __result.__tezz_body ? __result.__tezz_body : (__result || {});`);
    this.line(`res.writeHead(__status, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });`);
    this.line(`res.end(JSON.stringify(__respBody));`);
    this.indent--;
    this.line(`} catch (__err) {`);
    this.indent++;
    this.line(`console.error('Tezz Error:', __err);`);
    this.line(`res.writeHead(500, { 'Content-Type': 'application/json' });`);
    this.line(`res.end(JSON.stringify({ error: __err.message }));`);
    this.indent--;
    this.line(`}`);
    this.line(`return;`);

    this.indent--;
    this.line(`}`);
    this.indent--;
    this.line(`}`);
    this.emit('\n');

    // 404
    this.line(`res.writeHead(404, { 'Content-Type': 'application/json' });`);
    this.line(`res.end(JSON.stringify({ error: 'Not Found', path: __path }));`);

    this.indent--;
    this.line(`});`);
    this.emit('\n');

    // Listen
    this.line(`__tezz_server_${svcName}.listen(${port}, () => {`);
    this.indent++;
    this.line(`console.log('');`);
    this.line(`console.log('  Tezz Service: ${svcName}');`);
    this.line(`console.log('  ✦ Running on http://localhost:' + ${port});`);
    this.line(`console.log('  ✦ Target: Node.js');`);
    this.line(`console.log('');`);
    this.indent--;
    this.line(`});`);
  }

  // --- Cloudflare Worker Server ---
  genWorkerServer(svcName) {
    this.line(`export default {`);
    this.indent++;
    this.line(`async fetch(req, env, ctx) {`);
    this.indent++;

    // CORS preflight
    this.line(`if (req.method === 'OPTIONS') {`);
    this.indent++;
    this.line(`return new Response(null, {`);
    this.indent++;
    this.line(`status: 204,`);
    this.line(`headers: {`);
    this.indent++;
    this.line(`'Access-Control-Allow-Origin': '*',`);
    this.line(`'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',`);
    this.line(`'Access-Control-Allow-Headers': 'Content-Type, Authorization',`);
    this.indent--;
    this.line(`},`);
    this.indent--;
    this.line(`});`);
    this.indent--;
    this.line(`}`);
    this.emit('\n');

    this.line(`const __url = new URL(req.url);`);
    this.line(`const __method = req.method;`);
    this.line(`const __path = __url.pathname;`);
    this.emit('\n');

    this.line(`for (const __route of __tezz_routes_${svcName}) {`);
    this.indent++;
    this.line(`const __match = __route.pattern.exec(__path);`);
    this.line(`if (__match && __route.method === __method) {`);
    this.indent++;

    this.line(`const __params = {};`);
    this.line(`__route.paramNames.forEach((n, i) => { __params[n] = __match[i + 1]; });`);
    this.emit('\n');

    this.line(`let __bodyData = {};`);
    this.line(`try { __bodyData = await req.json(); } catch {}`);
    this.emit('\n');

    this.line(`const __request = {`);
    this.indent++;
    this.line(`method: __method,`);
    this.line(`url: __path,`);
    this.line(`headers: Object.fromEntries(req.headers),`);
    this.line(`json() { return __bodyData; },`);
    this.line(`text() { return JSON.stringify(__bodyData); },`);
    this.line(`query: Object.fromEntries(__url.searchParams),`);
    this.indent--;
    this.line(`};`);
    this.emit('\n');

    this.line(`try {`);
    this.indent++;
    this.line(`const __result = await __route.handler(__request, __params);`);
    this.line(`const __status = __result && __result.__tezz_status ? __result.__tezz_status : 200;`);
    this.line(`const __respBody = __result && __result.__tezz_body ? __result.__tezz_body : (__result || {});`);
    this.line(`return new Response(JSON.stringify(__respBody), {`);
    this.indent++;
    this.line(`status: __status,`);
    this.line(`headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },`);
    this.indent--;
    this.line(`});`);
    this.indent--;
    this.line(`} catch (__err) {`);
    this.indent++;
    this.line(`return new Response(JSON.stringify({ error: __err.message }), {`);
    this.indent++;
    this.line(`status: 500,`);
    this.line(`headers: { 'Content-Type': 'application/json' },`);
    this.indent--;
    this.line(`});`);
    this.indent--;
    this.line(`}`);

    this.indent--;
    this.line(`}`);
    this.indent--;
    this.line(`}`);
    this.emit('\n');

    // 404
    this.line(`return new Response(JSON.stringify({ error: 'Not Found', path: __path }), {`);
    this.indent++;
    this.line(`status: 404,`);
    this.line(`headers: { 'Content-Type': 'application/json' },`);
    this.indent--;
    this.line(`});`);

    this.indent--;
    this.line(`},`);
    this.indent--;
    this.line(`};`);
  }

  // === EXPRESSIONS ===

  genExpr(node) {

    if (node.type === 'MacroInvocation') {
      const macro = this.macros[node.callee.name];
      if (!macro) throw new Error(`[Tezz Codegen] Macro not found: ${node.callee.name}`);
      const expandedBody = this.expandMacro(macro, node.arguments);
      
      const oldOutput = this.output;
      this.output = '';
      this.emit('(() => {\n');
      this.indent++;
      for (const s of expandedBody) this.genStmt(s);
      this.indent--;
      this.emit(''.padEnd(this.indent * 2, ' ') + '})()');
      
      const result = this.output;
      this.output = oldOutput;
      return result;
    }

    switch (node.type) {
      case 'NumberLiteral':        return String(node.value);
      case 'BooleanLiteral':       return String(node.value);
      case 'NullLiteral':          return 'null';
      case 'Identifier':           return node.name;
      case 'StringLiteral':        return this.genString(node);
      case 'BinaryExpression':     return `(${this.genExpr(node.left)} ${node.operator} ${this.genExpr(node.right)})`;
      case 'UnaryExpression':      return `(${node.operator}${this.genExpr(node.operand)})`;
      case 'AssignmentExpression': return `${this.genExpr(node.target)} = ${this.genExpr(node.value)}`;
      case 'AwaitExpression':      return `(await ${this.genExpr(node.argument)})`;
      case 'CallExpression':       return this.genCall(node);
      case 'MemberExpression':     return `${this.genExpr(node.object)}.${node.property}`;
      case 'IndexExpression':      return `${this.genExpr(node.object)}[${this.genExpr(node.index)}]`;
      case 'ArrayLiteral':         return `[${node.elements.map(e => this.genExpr(e)).join(', ')}]`;
      case 'ObjectLiteral':        return this.genObject(node);
      case 'ArrowFunction':        return this.genArrow(node);
      default: throw new Error(`[Tezz Codegen] Unknown expression: ${node.type}`);
    }
  }

  genString(node) {
    const val = node.value;
    // Check for Tezz string interpolation: "Hello, {name}!"
    if (val.includes('{') && val.includes('}')) {
      const tmpl = val
        .replace(/\\/g, '\\\\')
        .replace(/`/g, '\\`')
        .replace(/\{([^}]+)\}/g, '${$1}');
      return '`' + tmpl + '`';
    }
    return "'" + val.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
  }

  genCall(node) {
    const args = node.arguments.map(a => this.genExpr(a)).join(', ');

    // Built-in fetch() → await fetch()
    if (node.callee.type === 'Identifier' && node.callee.name === 'fetch') {
      return `(await fetch(${args}))`;
    }

    const callee = this.genExpr(node.callee);

    // .json() and .text() → await (may be on fetch result)
    if (node.callee.type === 'MemberExpression' &&
        (node.callee.property === 'json' || node.callee.property === 'text')) {
      return `(await ${callee}(${args}))`;
    }

    return `${callee}(${args})`;
  }

  genObject(node) {
    if (node.properties.length === 0) return '{}';
    const props = node.properties.map(p => {
      const key = /^[a-zA-Z_]\w*$/.test(p.key) ? p.key : `'${p.key}'`;
      return `${key}: ${this.genExpr(p.value)}`;
    });
    if (props.length <= 3) return `{ ${props.join(', ')} }`;
    // Multi-line for larger objects
    const inner = props.map(p => this.pad() + '  ' + p).join(',\n');
    return `{\n${inner}\n${this.pad()}}`;
  }

  genArrow(node) {
    const params = node.params.map(p => p.name).join(', ');
    if (node.isBlock) {
      const bodyLines = [];
      for (const s of node.body) {
        // Capture the generated statement
        const prevOutput = this.output;
        this.genStmt(s);
        const newCode = this.output.slice(prevOutput.length);
        bodyLines.push(newCode);
        this.output = prevOutput;
      }
      return `(${params}) => { ${bodyLines.join('').trim()} }`;
    }
    return `(${params}) => ${this.genExpr(node.body)}`;
  }
}

module.exports = { CodeGenerator };
